"use client";

import { DesignAlert, DesignBadge, DesignButton } from "@/components/design-components";
import { Link } from "@/components/link";
import {
  discardGrowthAdminFindingPageDraft,
  getGrowthAdminFindingPage,
  publishGrowthAdminFindingPageDraft,
  saveGrowthAdminFindingPageDraft,
} from "@/lib/growth/growth-api";
import { buildGrowthFindingPagePrompt } from "@/lib/growth/growth-page-prompt";
import type { GrowthAdminFindingPage } from "@/lib/growth/growth-types";
import { captureError, throwErr } from "@hexclave/shared/dist/utils/errors";
import { runAsynchronously } from "@hexclave/shared/dist/utils/promises";
import { urlString } from "@hexclave/shared/dist/utils/urls";
import { useStackApp, useUser } from "@hexclave/next";
import { ArrowLeftIcon } from "@phosphor-icons/react";
import { useParams, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { PageLayout } from "../../../../page-layout";
import { useProjectId } from "../../../../use-admin-app";
import { GrowthAdminDocumentEditor } from "../../document-editor";

type Loadable =
  | { status: "loading" }
  | { status: "error", message: string }
  | { status: "loaded", page: GrowthAdminFindingPage };

export default function PageClient() {
  useUser({ or: "redirect", projectIdMustMatch: "internal" });
  if (useProjectId() !== "internal") throwErr("Growth Admin must be opened from the internal project.");
  const app = useStackApp();
  const params = useParams<{ findingId: string }>();
  const targetProjectId = useSearchParams().get("targetProjectId") ?? throwErr("Evidence admin page requires targetProjectId.");
  const [data, setData] = useState<Loadable>({ status: "loading" });

  const load = useCallback(async () => {
    try {
      setData({ status: "loaded", page: await getGrowthAdminFindingPage(app, targetProjectId, params.findingId) });
    } catch (error) {
      captureError("growth-admin-finding-page-load", error);
      setData({ status: "error", message: error instanceof Error ? error.message : String(error) });
    }
  }, [app, params.findingId, targetProjectId]);

  useEffect(() => runAsynchronously(load()), [load]);

  const backLink = (
    <DesignButton asChild variant="ghost" size="sm" className="-ml-3 text-muted-foreground">
      <Link href={urlString`/projects/internal/gtm/admin?targetProjectId=${targetProjectId}`}>
        <ArrowLeftIcon className="size-4" /> Back to Growth Admin
      </Link>
    </DesignButton>
  );

  return (
    <PageLayout
      allowContentOverflow
      width={1200}
      title={data.status === "loaded" ? `${data.page.finding.title} · Growth Admin` : "Evidence page · Growth Admin"}
      description="Edit the customer-facing evidence or note page"
      backLink={backLink}
    >
      {data.status === "loading" ? <div className="h-64 animate-pulse rounded-2xl border bg-foreground/[0.03]" />
        : data.status === "error" ? (
          <DesignAlert variant="error"><div className="flex items-center justify-between gap-3"><span>{data.message}</span><DesignButton size="sm" variant="outline" onClick={load}>Retry</DesignButton></div></DesignAlert>
        ) : (
          <div className="space-y-5">
            <div className="flex flex-wrap items-center gap-2">
              <DesignBadge label={data.page.finding.kind === "note" ? "Note" : "Evidence"} color="cyan" size="sm" />
              {data.page.finding.category != null && <DesignBadge label={data.page.finding.category} color="blue" size="sm" />}
              <span className="text-xs text-muted-foreground">Generated by {data.page.finding.source}</span>
            </div>
            <GrowthAdminDocumentEditor
              contentKey={`${data.page.finding.id}:${data.page.draft?.updatedAtMillis ?? "none"}:${data.page.publishedAtMillis ?? "generated"}`}
              noun={data.page.finding.kind === "note" ? "note page" : "evidence page"}
              prompt={buildGrowthFindingPagePrompt(data.page.finding)}
              promptButtonLabel={data.page.finding.kind === "note" ? "Copy note-page prompt" : "Copy evidence-page prompt"}
              subtitle="Paste, preview, then publish the page the customer reads"
              liveDocument={data.page.finding.document ?? null}
              initialDraft={data.page.draft}
              publishedAtMillis={data.page.publishedAtMillis}
              saveDraft={async (input) => await saveGrowthAdminFindingPageDraft(app, targetProjectId, params.findingId, input)}
              publishDraft={async (expected) => {
                await publishGrowthAdminFindingPageDraft(app, targetProjectId, params.findingId, expected);
                await load();
              }}
              discardDraft={async () => {
                await discardGrowthAdminFindingPageDraft(app, targetProjectId, params.findingId);
                await load();
              }}
            />
          </div>
        )}
    </PageLayout>
  );
}
